name: Main
on:
  push:
    branches:
      - main

jobs:
  test-build-release:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
        run: |
          mkdir -p public
          cat resume.json | npx jsonresume-theme-even > public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: resume.beatriz.me
